### PR TITLE
fix: Overflowing text on home screen

### LINKED ISSUE #31: Undesired UI of Home Screen on some screen-sizes
The UI on home screen tends to misbehave for some screens.

Screenshot - 

> The behavior was seen on device - Moto g60 (size - 6.8 inches)

**It can be adjusted for various screen sizes by reducing the font size or the size constraints of containers for a proper seamless display**

### PR DESCRIPTION
**Pull request by ItsAdityaKSingh**
Fixes #31 
Tried fixing text and container sizings

### CODE REVIEW

**Comment by ItsAdityaKSingh** [comment]
@parthg48 Could you test these changes on your local device and let me know if the issue persists?

**Review by Arjupta — COMMENTED** [review]
Though you tried to solve this issue but I want to understand how have you calculated specific ratios. Also I am still facing overflow issue for the hamburger icon in the top right. I think it is better to remove the hamburger icon for now as it seems unnecessary. WDYT?

**Comment by ItsAdityaKSingh** [comment]
Yes, @ARJUPTA. Those changes were just temporary for testing and avoiding errors faced by @parthg48. I had planned to remove those bugs once and then put a standard value for all screens. 
Surely as we have no functionality of it, we could remove it.

**Review by Arjupta — COMMENTED** [review]
@ItsAdityaKSingh Okay then do the neccessary changes and let me know

**Review by Arjupta — APPROVED** [review]
Resolved latest conflicts and it LGTM

**Pull request merged**
